/** Decoupage en vigueur : 69 wilayas, 1541 communes (loi 26-06, JO n 25 du 5 avril 2026). Stocke en texte. */
export const WILAYAS: { code: string; name: string }[] = [
  {
    "code": "01",
    "name": "Adrar"
  },
  {
    "code": "02",
    "name": "Chlef"
  },
  {
    "code": "03",
    "name": "Laghouat"
  },
  {
    "code": "04",
    "name": "Oum El Bouaghi"
  },
  {
    "code": "05",
    "name": "Batna"
  },
  {
    "code": "06",
    "name": "Bejaia"
  },
  {
    "code": "07",
    "name": "Biskra"
  },
  {
    "code": "08",
    "name": "Bechar"
  },
  {
    "code": "09",
    "name": "Blida"
  },
  {
    "code": "10",
    "name": "Bouira"
  },
  {
    "code": "11",
    "name": "Tamanrasset"
  },
  {
    "code": "12",
    "name": "Tebessa"
  },
  {
    "code": "13",
    "name": "Tlemcen"
  },
  {
    "code": "14",
    "name": "Tiaret"
  },
  {
    "code": "15",
    "name": "Tizi Ouzou"
  },
  {
    "code": "16",
    "name": "Alger"
  },
  {
    "code": "17",
    "name": "Djelfa"
  },
  {
    "code": "18",
    "name": "Jijel"
  },
  {
    "code": "19",
    "name": "Setif"
  },
  {
    "code": "20",
    "name": "Saida"
  },
  {
    "code": "21",
    "name": "Skikda"
  },
  {
    "code": "22",
    "name": "Sidi Bel Abbes"
  },
  {
    "code": "23",
    "name": "Annaba"
  },
  {
    "code": "24",
    "name": "Guelma"
  },
  {
    "code": "25",
    "name": "Constantine"
  },
  {
    "code": "26",
    "name": "Medea"
  },
  {
    "code": "27",
    "name": "Mostaganem"
  },
  {
    "code": "28",
    "name": "M'Sila"
  },
  {
    "code": "29",
    "name": "Mascara"
  },
  {
    "code": "30",
    "name": "Ouargla"
  },
  {
    "code": "31",
    "name": "Oran"
  },
  {
    "code": "32",
    "name": "El Bayadh"
  },
  {
    "code": "33",
    "name": "Illizi"
  },
  {
    "code": "34",
    "name": "Bordj Bou Arreridj"
  },
  {
    "code": "35",
    "name": "Boumerdes"
  },
  {
    "code": "36",
    "name": "El Tarf"
  },
  {
    "code": "37",
    "name": "Tindouf"
  },
  {
    "code": "38",
    "name": "Tissemsilt"
  },
  {
    "code": "39",
    "name": "El Oued"
  },
  {
    "code": "40",
    "name": "Khenchela"
  },
  {
    "code": "41",
    "name": "Souk Ahras"
  },
  {
    "code": "42",
    "name": "Tipaza"
  },
  {
    "code": "43",
    "name": "Mila"
  },
  {
    "code": "44",
    "name": "Ain Defla"
  },
  {
    "code": "45",
    "name": "Naama"
  },
  {
    "code": "46",
    "name": "Ain Temouchent"
  },
  {
    "code": "47",
    "name": "Ghardaia"
  },
  {
    "code": "48",
    "name": "Relizane"
  },
  {
    "code": "49",
    "name": "Timimoun"
  },
  {
    "code": "50",
    "name": "Bordj Badji Mokhtar"
  },
  {
    "code": "51",
    "name": "Ouled Djellal"
  },
  {
    "code": "52",
    "name": "Beni Abbes"
  },
  {
    "code": "53",
    "name": "In Salah"
  },
  {
    "code": "54",
    "name": "In Guezzam"
  },
  {
    "code": "55",
    "name": "Touggourt"
  },
  {
    "code": "56",
    "name": "Djanet"
  },
  {
    "code": "57",
    "name": "El M'Ghair"
  },
  {
    "code": "58",
    "name": "El Meniaa"
  },
  {
    "code": "59",
    "name": "Aflou"
  },
  {
    "code": "60",
    "name": "Barika"
  },
  {
    "code": "61",
    "name": "El Kantara"
  },
  {
    "code": "62",
    "name": "Bir El Ater"
  },
  {
    "code": "63",
    "name": "El Aricha"
  },
  {
    "code": "64",
    "name": "Ksar Chellala"
  },
  {
    "code": "65",
    "name": "Ain Oussara"
  },
  {
    "code": "66",
    "name": "Messaad"
  },
  {
    "code": "67",
    "name": "Ksar El Boukhari"
  },
  {
    "code": "68",
    "name": "Bou Saada"
  },
  {
    "code": "69",
    "name": "El Abiodh Sidi Cheikh"
  }
];

export const COMMUNES_BY_WILAYA: Record<string, readonly string[]> = {
  "Adrar": [
    "Adrar",
    "Akabli",
    "Aoulef",
    "Bouda",
    "Fenoughil",
    "In Zghmir",
    "Ouled Ahmed Timmi",
    "Reggane",
    "Sali",
    "Sebaa",
    "Tamantit",
    "Tamest",
    "Timekten",
    "Tit",
    "Tsabit",
    "Zaouiet Kounta"
  ],
  "Chlef": [
    "Abou El Hassane",
    "Ain Merane",
    "Benairia",
    "Beni  Bouattab",
    "Beni Haoua",
    "Beni Rached",
    "Boukadir",
    "Bouzeghaia",
    "Breira",
    "Chettia",
    "Chlef",
    "Dahra",
    "El Hadjadj",
    "El Karimia",
    "El Marsa",
    "Harchoun",
    "Herenfa",
    "Labiod Medjadja",
    "Moussadek",
    "Oued Fodda",
    "Oued Goussine",
    "Oued Sly",
    "Ouled Abbes",
    "Ouled Ben Abdelkader",
    "Ouled Fares",
    "Oum Drou",
    "Sendjas",
    "Sidi Abderrahmane",
    "Sidi Akkacha",
    "Sobha",
    "Tadjena",
    "Talassa",
    "Taougrit",
    "Tenes",
    "Zeboudja"
  ],
  "Laghouat": [
    "Ain Madhi",
    "Benacer Benchohra",
    "El Assafia",
    "El Haouita",
    "Hassi Delaa",
    "Hassi R’Mel",
    "Kheneg",
    "Ksar El Hirane",
    "Laghouat",
    "Sidi Makhlouf",
    "Tadjemout",
    "Tadjrouna"
  ],
  "Oum El Bouaghi": [
    "Ain Babouche",
    "Ain Beida",
    "Ain Diss",
    "Ain Fekroun",
    "Ain Kercha",
    "Ain M'lila",
    "Ain Zitoun",
    "Behir Chergui",
    "Berriche",
    "Bir Chouhada",
    "Dhalaa",
    "El Amiria",
    "El Belala",
    "El Djazia",
    "El Fedjoudj Boughrara Sa",
    "El Harmilia",
    "Fkirina",
    "Hanchir Toumghani",
    "Ksar Sbahi",
    "Meskiana",
    "Oued Nini",
    "Ouled Gacem",
    "Ouled Hamla",
    "Ouled Zouai",
    "Oum El Bouaghi",
    "Rahia",
    "Sigus",
    "Souk Naamane",
    "Zorg"
  ],
  "Batna": [
    "Ain Djasser",
    "Ain Touta",
    "Ain Yagout",
    "Arris",
    "Batna",
    "Beni Fedhala El Hakania",
    "Boulhilat",
    "Boumagueur",
    "Boumia",
    "Bouzina",
    "Chemora",
    "Chir",
    "Djerma",
    "El Hassi",
    "Elmadher",
    "Fesdis",
    "Foum Toub",
    "Ghassira",
    "Gosbat",
    "Guigba",
    "Hidoussa",
    "Ichmoul",
    "Inoughissene",
    "Kimmel",
    "Ksar Belezma",
    "Larbaa",
    "Lazrou",
    "Lemsane",
    "Maafa",
    "Menaa",
    "Merouana",
    "N’Gaous",
    "Oued Chaaba",
    "Oued El Ma",
    "Oued Taga",
    "Ouled Aouf",
    "Ouled Fadel",
    "Ouled Sellem",
    "Ouled Si Slimane",
    "Ouyoun El Assafir",
    "Rahbat",
    "Ras El Aioun",
    "Sefiane",
    "Seriana",
    "T’Kout",
    "Talkhamt",
    "Taxlent",
    "Tazoult",
    "Teniet El Abed",
    "Tighanimine",
    "Tigherghar",
    "Timgad",
    "Zana El Beida"
  ],
  "Bejaia": [
    "Adekar",
    "Ait R'zine",
    "Ait-Smail",
    "Akbou",
    "Akfadou",
    "Amalou",
    "Amizour",
    "Aokas",
    "Barbacha",
    "Bejaia",
    "Beni Djellil",
    "Beni K'sila",
    "Beni-Mallikeche",
    "Benimaouche",
    "Boudjellil",
    "Bouhamza",
    "Boukhelifa",
    "Chellata",
    "Chemini",
    "Darguina",
    "Dra El Caid",
    "El Kseur",
    "Fenaia Il Maten",
    "Feraoun",
    "Ighil-Ali",
    "Ighram",
    "Kendira",
    "Kherrata",
    "Leflaye",
    "M'cisna",
    "Melbou",
    "Oued Ghir",
    "Ouzellaguen",
    "Seddouk",
    "Sidi Ayad",
    "Sidi-Aich",
    "Smaoun",
    "Souk El Tenine",
    "Souk Oufella",
    "Tala Hamza",
    "Tamokra",
    "Tamridjet",
    "Taourit Ighil",
    "Taskriout",
    "Tazmalt",
    "Tibane",
    "Tichy",
    "Tifra",
    "Timezrit",
    "Tinebdar",
    "Tizi-N'berber",
    "Toudja"
  ],
  "Biskra": [
    "Ain Naga",
    "Biskra",
    "Bordj Ben Azzouz",
    "Bouchagroun",
    "Chetma",
    "El Feidh",
    "El Ghrous",
    "El Hadjeb",
    "El Haouch",
    "Foughala",
    "Khangat Sidi Nadji",
    "Lichana",
    "Lioua",
    "M’Chouneche",
    "M’Lili",
    "Mekhadma",
    "Meziraa",
    "Oumache",
    "Ourlal",
    "Sidi Okba",
    "Tolga",
    "Zeribet El Oued"
  ],
  "Bechar": [
    "Abadla",
    "Bechar",
    "Beni-Ounif",
    "Boukais",
    "Erg-Ferradj",
    "Kenadsa",
    "Lahmar",
    "Machraa-Houari-Boumediene",
    "Meridja",
    "Mogheul",
    "Tabelbala",
    "Taghit"
  ],
  "Blida": [
    "Ain Romana",
    "Beni Mered",
    "Beni-Tamou",
    "Benkhelil",
    "Blida",
    "Bouarfa",
    "Boufarik",
    "Bougara",
    "Bouinan",
    "Chebli",
    "Chiffa",
    "Chrea",
    "Djebabra",
    "El-Affroun",
    "Guerrouaou",
    "Hammam Elouane",
    "Larbaa",
    "Meftah",
    "Mouzaia",
    "Oued  Djer",
    "Oued El Alleug",
    "Ouled Slama",
    "Ouled Yaich",
    "Souhane",
    "Soumaa"
  ],
  "Bouira": [
    "Aghbalou",
    "Ahl El Ksar",
    "Ain El Hadjar",
    "Ain Laloui",
    "Ain Turk",
    "Ain-Bessem",
    "Ait Laaziz",
    "Aomar",
    "Ath Mansour",
    "Bechloul",
    "Bir Ghbalou",
    "Bordj Okhriss",
    "Bouderbala",
    "Bouira",
    "Boukram",
    "Chorfa",
    "Dechmia",
    "Dirah",
    "Djebahia",
    "El Adjiba",
    "El Asnam",
    "El Hachimia",
    "El Khabouzia",
    "El-Hakimia",
    "El-Mokrani",
    "Guerrouma",
    "Hadjera Zerga",
    "Haizer",
    "Hanif",
    "Kadiria",
    "Lakhdaria",
    "M Chedallah",
    "Maala",
    "Maamora",
    "Mezdour",
    "Oued El Berdi",
    "Ouled Rached",
    "Raouraoua",
    "Ridane",
    "Saharidj",
    "Souk El Khemis",
    "Sour El Ghozlane",
    "Taghzout",
    "Taguedite",
    "Z'barbar (El Isseri )"
  ],
  "Tamanrasset": [
    "Abelsa",
    "Ain Amguel",
    "Idles",
    "Tamanrasset",
    "Tazrouk"
  ],
  "Tebessa": [
    "Ain Zerga",
    "Bedjene",
    "Bekkaria",
    "Bir Dheheb",
    "Bir Mokkadem",
    "Boukhadra",
    "Boulhaf Dyr",
    "Cheria",
    "El Aouinet",
    "El Kouif",
    "El Ma Labiod",
    "El Meridj",
    "El Mezeraa",
    "El Ogla",
    "Gourrigueur",
    "Hammamet",
    "Lahouidjbet",
    "Morsott",
    "Ouenza",
    "Oum Ali",
    "Safsaf El Ouesra",
    "Stah Guentis",
    "Tebessa",
    "Thlidjene"
  ],
  "Tlemcen": [
    "Ain Fetah",
    "Ain Fezza",
    "Ain Ghoraba",
    "Ain Kebira",
    "Ain Nehala",
    "Ain Tallout",
    "Ain Youcef",
    "Amieur",
    "Azails",
    "Bab El Assa",
    "Beni Bahdel",
    "Beni Boussaid",
    "Beni Khellad",
    "Beni Mester",
    "Beni Ouarsous",
    "Beni Semiel",
    "Beni Snous",
    "Bensekrane",
    "Bouhlou",
    "Chetouane",
    "Dar Yaghmouracene",
    "Djebala",
    "El Fehoul",
    "Fellaoucene",
    "Ghazaouet",
    "Hammam Boughrara",
    "Hennaya",
    "Honaine",
    "Maghnia",
    "Mansourah",
    "Marsa Ben M’Hidi",
    "Msirda Fouaga",
    "Nedroma",
    "Oued Lakhdar",
    "Ouled Mimoun",
    "Ouled Riyah",
    "Remchi",
    "Sabra",
    "Sebaa Chioukh",
    "Sebdou",
    "Sidi Abdelli",
    "Sidi Medjahed",
    "Souahlia",
    "Souani",
    "Souk Thlata",
    "Tianet",
    "Tirni Beni Hediel",
    "Tlemcen",
    "Zenata"
  ],
  "Tiaret": [
    "Ain Bouchekif",
    "Ain Deheb",
    "Ain Dzarit",
    "Ain El Hadid",
    "Ain Kermes",
    "Chehaima",
    "Dahmouni",
    "Djebilet Rosfa",
    "Djileli Ben Amar",
    "Faidja",
    "Frenda",
    "Guertoufa",
    "Madna",
    "Mahdia",
    "Mechraa Sfa",
    "Medrissa",
    "Medroussa",
    "Meghila",
    "Mellakou",
    "Nadorah",
    "Naima",
    "Oued Lili",
    "Rahouia",
    "Sebaine",
    "Sebt",
    "Sidi Abdelghani",
    "Sidi Abderrahmane",
    "Sidi Ali Mellal",
    "Sidi Bakhti",
    "Sidi Hosni",
    "Sougueur",
    "Tagdemt",
    "Takhemaret",
    "Tiaret",
    "Tidda",
    "Tousnina"
  ],
  "Tizi Ouzou": [
    "Abi-Youcef",
    "Aghribs",
    "Agouni-Gueghrane",
    "Ain-El-Hammam",
    "Ain-Zaouia",
    "Ait Aggouacha",
    "Ait Bouaddou",
    "Ait Boumahdi",
    "Ait Khellili",
    "Ait Yahia Moussa",
    "Ait-Aissa-Mimoun",
    "Ait-Chafaa",
    "Ait-Mahmoud",
    "Ait-Oumalou",
    "Ait-Toudert",
    "Ait-Yahia",
    "Akbil",
    "Akerrou",
    "Assi-Youcef",
    "Azazga",
    "Azeffoun",
    "Beni Zmenzer",
    "Beni-Aissi",
    "Beni-Douala",
    "Beni-Yenni",
    "Beni-Zikki",
    "Boghni",
    "Boudjima",
    "Bounouh",
    "Bouzeguene",
    "Draa-Ben-Khedda",
    "Draa-El-Mizan",
    "Freha",
    "Frikat",
    "Iboudrarene",
    "Idjeur",
    "Iferhounene",
    "Ifigha",
    "Iflissen",
    "Illilten",
    "Illoula Oumalou",
    "Imsouhal",
    "Irdjen",
    "Larbaa Nath Irathen",
    "M'kira",
    "Maatkas",
    "Makouda",
    "Mechtras",
    "Mekla",
    "Mizrana",
    "Ouacif",
    "Ouadhias",
    "Ouaguenoun",
    "Sidi Namane",
    "Souama",
    "Souk-El-Tenine",
    "Tadmait",
    "Tigzirt",
    "Timizart",
    "Tirmitine",
    "Tizi N'tleta",
    "Tizi-Gheniff",
    "Tizi-Ouzou",
    "Tizi-Rached",
    "Yakourene",
    "Yatafene",
    "Zekri"
  ],
  "Alger": [
    "Ain Benian",
    "Ain Taya",
    "Alger Centre",
    "Bab El Oued",
    "Bab Ezzouar",
    "Baba Hassen",
    "Bachedjerah",
    "Baraki",
    "Ben Aknoun",
    "Beni Messous",
    "Bir Mourad Rais",
    "Bir Touta",
    "Birkhadem",
    "Bologhine Ibnou Ziri",
    "Bordj El Bahri",
    "Bordj El Kiffan",
    "Bourouba",
    "Bouzareah",
    "Casbah",
    "Cheraga",
    "Dar El Beida",
    "Dely Ibrahim",
    "Djasr Kasentina",
    "Douira",
    "Draria",
    "El Achour",
    "El Biar",
    "El Harrach",
    "El Madania",
    "El Magharia",
    "El Marsa",
    "El Mouradia",
    "Hammamet",
    "Herraoua",
    "Hussein Dey",
    "Hydra",
    "Khraissia",
    "Kouba",
    "Les Eucalyptus",
    "Maalma",
    "Mohamed Belouzdad",
    "Mohammadia",
    "Oued Koriche",
    "Oued Smar",
    "Ouled Chebel",
    "Ouled Fayet",
    "Rahmania",
    "Rais Hamidou",
    "Reghaia",
    "Rouiba",
    "Sehaoula",
    "Sidi M'hamed",
    "Sidi Moussa",
    "Souidania",
    "Staoueli",
    "Tessala El Merdja",
    "Zeralda"
  ],
  "Djelfa": [
    "Ain Chouhada",
    "Ain El Ibel",
    "Ain Maabed",
    "Ben Yaagoub",
    "Charef",
    "Dar Chioukh",
    "Djelfa",
    "Douis",
    "El Gueddid",
    "El Idrissia",
    "Hassi Bahbah",
    "Hassi El Euch",
    "M’Liliha",
    "Moudjbara",
    "Sidi Baizid",
    "Tadmit",
    "Zaafrane",
    "Zaccar"
  ],
  "Jijel": [
    "Bordj T'har",
    "Boudria Beniyadjis",
    "Bouraoui Belhadef",
    "Boussif Ouled Askeur",
    "Chahna",
    "Chekfa",
    "Djemaa Beni Habibi",
    "Djimla",
    "El Ancer",
    "El Aouana",
    "El Kennar Nouchfi",
    "El Milia",
    "Emir Abdelkader",
    "Erraguene Souissi",
    "Ghebala",
    "Jijel",
    "Kaous",
    "Khiri Oued Adjoul",
    "Oudjana",
    "Ouled Rabah",
    "Ouled Yahia Khadrouch",
    "Selma Benziada",
    "Settara",
    "Sidi Abdelaziz",
    "Sidi Marouf",
    "Taher",
    "Texenna",
    "Ziama Mansouriah"
  ],
  "Setif": [
    "Ain Abessa",
    "Ain Arnat",
    "Ain Azel",
    "Ain El Kebira",
    "Ain Lahdjar",
    "Ain Oulmene",
    "Ain-Legradj",
    "Ain-Roua",
    "Ain-Sebt",
    "Ait Naoual Mezada",
    "Ait-Tizi",
    "Amoucha",
    "Babor",
    "Bazer-Sakra",
    "Beidha Bordj",
    "Bellaa",
    "Beni Chebana",
    "Beni Fouda",
    "Beni Ourtilane",
    "Beni Oussine",
    "Beni-Aziz",
    "Beni-Mouhli",
    "Bir Haddada",
    "Bir-El-Arch",
    "Bouandas",
    "Bougaa",
    "Bousselam",
    "Boutaleb",
    "Dehamcha",
    "Djemila",
    "Draa-Kebila",
    "El Eulma",
    "El Ouricia",
    "El-Ouldja",
    "Guellal",
    "Guelta Zerka",
    "Guenzet",
    "Guidjel",
    "Hamam Soukhna",
    "Hamma",
    "Hammam Guergour",
    "Harbil",
    "Kasr El Abtal",
    "Maaouia",
    "Maouaklane",
    "Mezloug",
    "Oued El Bared",
    "Ouled Addouane",
    "Ouled Sabor",
    "Ouled Si Ahmed",
    "Ouled Tebben",
    "Rosfa",
    "Salah Bey",
    "Serdj-El-Ghoul",
    "Setif",
    "Tachouda",
    "Tala-Ifacene",
    "Taya",
    "Tella",
    "Tizi N'bechar"
  ],
  "Saida": [
    "Ain El Hadjar",
    "Ain Sekhouna",
    "Ain Soltane",
    "Doui Thabet",
    "El Hassasna",
    "Hounet",
    "Maamora",
    "Moulay Larbi",
    "Ouled Brahim",
    "Ouled Khaled",
    "Saida",
    "Sidi Ahmed",
    "Sidi Amar",
    "Sidi Boubekeur",
    "Tircine",
    "Youb"
  ],
  "Skikda": [
    "Ain Bouziane",
    "Ain Charchar",
    "Ain Kechra",
    "Ain Zouit",
    "Azzaba",
    "Bekkouche Lakhdar",
    "Ben Azzouz",
    "Beni Bechir",
    "Beni Oulbane",
    "Beni Zid",
    "Bin El Ouiden",
    "Bouchetata",
    "Cheraia",
    "Collo",
    "Djendel Saadi Mohamed",
    "El Arrouch",
    "El Ghedir",
    "El Hadaiek",
    "El Marsa",
    "Emjez Edchich",
    "Es Sebt",
    "Filfila",
    "Hammadi Krouma",
    "Kanoua",
    "Kerkara",
    "Khenag Maoune",
    "Oued Zhour",
    "Ouldja Boulbalout",
    "Ouled Attia",
    "Ouled Habbaba",
    "Oum Toub",
    "Ramdane Djamel",
    "Salah Bouchaour",
    "Sidi Mezghiche",
    "Skikda",
    "Tamalous",
    "Zerdezas",
    "Zitouna"
  ],
  "Sidi Bel Abbes": [
    "Ain El Berd",
    "Ain Kada",
    "Ain Thrid",
    "Ain Tindamine",
    "Ain- Adden",
    "Amarnas",
    "Bedrabine El Mokrani",
    "Belarbi",
    "Ben Badis",
    "Benachiba Chelia",
    "Bir El Hammam",
    "Boudjebaa El Bordj",
    "Boukhanefis",
    "Chetouane Belaila",
    "Dhaya",
    "El Hacaiba",
    "Hassi Dahou",
    "Hassi Zahana",
    "Lamtar",
    "M'cid",
    "Makedra",
    "Marhoum",
    "Merine",
    "Mezaourou",
    "Mostefa  Ben Brahim",
    "Moulay Slissen",
    "Oued Sebaa",
    "Oued Sefioun",
    "Oued Taourira",
    "Ras El Ma",
    "Redjem Demouche",
    "Sehala Thaoura",
    "Sfisef",
    "Sidi Ali Benyoub",
    "Sidi Ali Boussidi",
    "Sidi Bel-Abbes",
    "Sidi Brahim",
    "Sidi Chaib",
    "Sidi Dahou Zairs",
    "Sidi Hamadouche",
    "Sidi Khaled",
    "Sidi Lahcene",
    "Sidi Yacoub",
    "Tabia",
    "Taoudmout",
    "Tefessour",
    "Teghalimet",
    "Telagh",
    "Tenira",
    "Tessala",
    "Tilmouni",
    "Zerouala"
  ],
  "Annaba": [
    "Ain El Berda",
    "Annaba",
    "Berrahal",
    "Chetaibi",
    "Cheurfa",
    "El Bouni",
    "El Eulma",
    "El Hadjar",
    "Oued El Aneb",
    "Seraidi",
    "Sidi Amar",
    "Treat"
  ],
  "Guelma": [
    "Ain Ben Beida",
    "Ain Larbi",
    "Ain Makhlouf",
    "Ain Regada",
    "Ain Sandel",
    "Belkheir",
    "Bendjarah",
    "Beni Mezline",
    "Bordj Sabath",
    "Bou Hachana",
    "Bou Hamdane",
    "Bouati Mahmoud",
    "Bouchegouf",
    "Boumahra Ahmed",
    "Dahouara",
    "Djeballah Khemissi",
    "El Fedjoudj",
    "Guelaat Bou Sbaa",
    "Guelma",
    "Hammam Debagh",
    "Hammam N'bail",
    "Heliopolis",
    "Houari Boumedienne",
    "Khezaras",
    "Medjez Amar",
    "Medjez Sfa",
    "Nechmaya",
    "Oued Cheham",
    "Oued Ferragha",
    "Oued Zenati",
    "Ras El Agba",
    "Roknia",
    "Sellaoua Announa",
    "Tamlouka"
  ],
  "Constantine": [
    "Ain Abid",
    "Ain Smara",
    "Ben Badis",
    "Beni Hamidane",
    "Constantine",
    "Didouche Mourad",
    "El Khroub",
    "Hamma Bouziane",
    "Ibn Ziad",
    "Messaoud Boudjeriou",
    "Ouled Rahmoun",
    "Zighoud Youcef"
  ],
  "Medea": [
    "Aissaouia",
    "Al Azizia",
    "Baata",
    "Benchicao",
    "Beni Slimane",
    "Berrouaghia",
    "Bir Ben Abed",
    "Bouaichoune",
    "Bouchrahil",
    "Bouskene",
    "Deux Bassins",
    "Djouab",
    "Draa Essamar",
    "Eddouair",
    "El Guelb El Kebir",
    "El Hamdania",
    "El Omaria",
    "Hannacha",
    "Khamsa Djoumaa",
    "Medea",
    "Medjebar",
    "Meghraoua",
    "Mezghenna",
    "Mihoub",
    "Ouamri",
    "Oued Harbil",
    "Ouled Bouachra",
    "Ouled Brahim",
    "Ouled Deide",
    "Ouzera",
    "Rebaia",
    "Sedraia",
    "Seghouane",
    "Si Mahdjoub",
    "Sidi Errabie",
    "Sidi Naamane",
    "Sidi Zahar",
    "Sidi Ziane",
    "Souagui",
    "Tablat",
    "Tamezguida",
    "Tizi Mahdi",
    "Zoubiria"
  ],
  "Mostaganem": [
    "Achaacha",
    "Ain-Boudinar",
    "Ain-Nouissy",
    "Ain-Sidi Cherif",
    "Ain-Tedles",
    "Benabdelmalek Ramdane",
    "Bouguirat",
    "Fornaka",
    "Hadjadj",
    "Hassi Mameche",
    "Hassiane",
    "Khadra",
    "Kheir-Eddine",
    "Mansourah",
    "Mazagran",
    "Mesra",
    "Mostaganem",
    "Nekmaria",
    "Oued El Kheir",
    "Ouled Boughalem",
    "Ouled-Maalah",
    "Safsaf",
    "Sayada",
    "Sidi Ali",
    "Sidi Belaattar",
    "Sidi-Lakhdar",
    "Sirat",
    "Souaflia",
    "Sour",
    "Stidia",
    "Tazgait",
    "Touahria"
  ],
  "M'Sila": [
    "Ain El Hadjel",
    "Ain Khadra",
    "Belaiba",
    "Beni Ilmane",
    "Berhoum",
    "Bouti Sayah",
    "Chellal",
    "Dehahna",
    "Hammam Dhalaa",
    "Khetouti Sed El Djir",
    "M’Sila",
    "M’Tarfa",
    "Maadid",
    "Maarif",
    "Magra",
    "Ouanougha",
    "Ouled Addi Guebala",
    "Ouled Derradj",
    "Ouled Madhi",
    "Ouled Mansour",
    "Sidi Aissa",
    "Sidi Hadjeres",
    "Souamaa",
    "Tarmount"
  ],
  "Mascara": [
    "Ain Fares",
    "Ain Fekan",
    "Ain Ferah",
    "Ain Frass",
    "Alaimia",
    "Aouf",
    "Benian",
    "Bou Henni",
    "Bouhanifia",
    "Chorfa",
    "El Bordj",
    "El Gaada",
    "El Ghomri",
    "El Gueitena",
    "El Hachem",
    "El Keurt",
    "El Mamounia",
    "El Menaouer",
    "Ferraguig",
    "Froha",
    "Gharrous",
    "Ghriss",
    "Guerdjoum",
    "Hacine",
    "Khalouia",
    "Makhda",
    "Maoussa",
    "Mascara",
    "Matemore",
    "Mocta-Douz",
    "Mohammadia",
    "Nesmot",
    "Oggaz",
    "Oued El Abtal",
    "Oued Taria",
    "Ras El Ain Amirouche",
    "Sedjerara",
    "Sehailia",
    "Sidi Abdeldjebar",
    "Sidi Abdelmoumene",
    "Sidi Boussaid",
    "Sidi Kada",
    "Sig",
    "Tighennif",
    "Tizi",
    "Zahana",
    "Zelamta"
  ],
  "Ouargla": [
    "Ain Beida",
    "El Borma",
    "Hassi Ben Abdellah",
    "Hassi Messaoud",
    "N'goussa",
    "Ouargla",
    "Rouissat",
    "Sidi Khouiled"
  ],
  "Oran": [
    "Ain Biya",
    "Ain Kerma",
    "Ain Turk",
    "Arzew",
    "Ben Freha",
    "Bethioua",
    "Bir El Djir",
    "Boufatis",
    "Bousfer",
    "Boutlelis",
    "El Ancor",
    "El Braya",
    "El Kerma",
    "Es Senia",
    "Gdyel",
    "Hassi Ben Okba",
    "Hassi Bounif",
    "Hassi Mefsoukh",
    "Marsat El Hadjadj",
    "Mers El Kebir",
    "Messerghin",
    "Oran",
    "Oued Tlelat",
    "Sidi Ben Yebka",
    "Sidi Chami",
    "Tafraoui"
  ],
  "El Bayadh": [
    "Boualem",
    "Bougtob",
    "Brezina",
    "Cheguig",
    "El Bayadh",
    "El Kheither",
    "Ghassoul",
    "Kef El Ahmar",
    "Krakda",
    "Rogassa",
    "Sidi Amar",
    "Sidi Slimane",
    "Sidi Tifour",
    "Stitten",
    "Tousmouline"
  ],
  "Illizi": [
    "Bordj Omar Driss",
    "Debdeb",
    "Illizi",
    "In Amenas"
  ],
  "Bordj Bou Arreridj": [
    "Ain Taghrout",
    "Ain Tesra",
    "B. B. Arreridj",
    "Belimour",
    "Ben Daoud",
    "Bir Kasdali",
    "Bordj Ghedir",
    "Bordj Zemmoura",
    "Colla",
    "Djaafra",
    "El Achir",
    "El Annasseur",
    "El Euch",
    "El M'hir",
    "El Main",
    "Elhammadia",
    "Ghailasa",
    "Haraza",
    "Hasnaoua",
    "Khelil",
    "Ksour",
    "Mansoura",
    "Medjana",
    "Ouled Brahem",
    "Ouled Dahmane",
    "Ouled Sidi-Brahim",
    "Rabta",
    "Ras El Oued",
    "Sidi-Embarek",
    "Taglait",
    "Tassamert",
    "Tefreg",
    "Teniet En Nasr",
    "Tixter"
  ],
  "Boumerdes": [
    "Afir",
    "Ammal",
    "Baghlia",
    "Ben Choud",
    "Beni Amrane",
    "Bordj Menaiel",
    "Boudouaou",
    "Boudouaou El Bahri",
    "Boumerdes",
    "Bouzegza Keddara",
    "Chabet El Ameur",
    "Corso",
    "Dellys",
    "Djinet",
    "El Kharrouba",
    "Hammedi",
    "Isser",
    "Khemis El Khechna",
    "Larbatache",
    "Leghata",
    "Naciria",
    "Ouled Aissa",
    "Ouled Hedadj",
    "Ouled Moussa",
    "Si Mustapha",
    "Sidi Daoud",
    "Souk El Had",
    "Taourga",
    "Thenia",
    "Tidjelabine",
    "Timezrit",
    "Zemmouri"
  ],
  "El Tarf": [
    "Ain El Assel",
    "Ain Kerma",
    "Asfour",
    "Ben M Hidi",
    "Berrihane",
    "Besbes",
    "Bougous",
    "Bouhadjar",
    "Bouteldja",
    "Chebaita Mokhtar",
    "Chefia",
    "Chihani",
    "Drean",
    "Echatt",
    "El Aioun",
    "El Kala",
    "El Tarf",
    "Hammam Beni Salah",
    "Lac Des Oiseaux",
    "Oued Zitoun",
    "Raml Souk",
    "Souarekh",
    "Zerizer",
    "Zitouna"
  ],
  "Tindouf": [
    "Oum El Assel",
    "Tindouf"
  ],
  "Tissemsilt": [
    "Ammari",
    "Beni Chaib",
    "Beni Lahcene",
    "Bordj Bounaama",
    "Bordj El Emir Abdelkader",
    "Boucaid",
    "Khemisti",
    "Larbaa",
    "Lardjem",
    "Layoune",
    "Lazharia",
    "Maacem",
    "Melaab",
    "Ouled Bessam",
    "Sidi Abed",
    "Sidi Boutouchent",
    "Sidi Lantri",
    "Sidi Slimane",
    "Tamellahet",
    "Theniet El Had",
    "Tissemsilt",
    "Youssoufia"
  ],
  "El Oued": [
    "Bayadha",
    "Ben Guecha",
    "Debila",
    "Douar El Maa",
    "El Ogla",
    "El-Oued",
    "Guemar",
    "Hamraia",
    "Hassani Abdelkrim",
    "Hassi Khalifa",
    "Kouinine",
    "Magrane",
    "Mih Ouansa",
    "Nakhla",
    "Oued El Alenda",
    "Ourmes",
    "Reguiba",
    "Robbah",
    "Sidi Aoun",
    "Taghzout",
    "Taleb Larbi",
    "Trifaoui"
  ],
  "Khenchela": [
    "Ain Touila",
    "Babar",
    "Baghai",
    "Bouhmama",
    "Chechar",
    "Chelia",
    "Djellal",
    "El Hamma",
    "El Mahmal",
    "El Oueldja",
    "Ensigha",
    "Kais",
    "Khenchela",
    "Khirane",
    "M'sara",
    "M'toussa",
    "Ouled Rechache",
    "Remila",
    "Tamza",
    "Taouzianat",
    "Yabous"
  ],
  "Souk Ahras": [
    "Ain Soltane",
    "Ain Zana",
    "Bir Bouhouche",
    "Drea",
    "Haddada",
    "Hanencha",
    "Khedara",
    "Khemissa",
    "M'daourouche",
    "Machroha",
    "Merahna",
    "Oued Kebrit",
    "Ouillen",
    "Ouled Driss",
    "Ouled Moumen",
    "Oum El Adhaim",
    "Ragouba",
    "Safel El Ouiden",
    "Sedrata",
    "Sidi Fredj",
    "Souk Ahras",
    "Taoura",
    "Terraguelt",
    "Tiffech",
    "Zaarouria",
    "Zouabi"
  ],
  "Tipaza": [
    "Aghbal",
    "Ahmer El Ain",
    "Ain Tagourait",
    "Attatba",
    "Beni Mileuk",
    "Bou Haroun",
    "Bou Ismail",
    "Bourkika",
    "Chaiba",
    "Cherchell",
    "Damous",
    "Douaouda",
    "Fouka",
    "Gouraya",
    "Hadjout",
    "Hadjret Ennous",
    "Khemisti",
    "Kolea",
    "Larhat",
    "Menaceur",
    "Merad",
    "Messelmoun",
    "Nador",
    "Sidi Ghiles",
    "Sidi Rached",
    "Sidi Semiane",
    "Sidi-Amar",
    "Tipaza"
  ],
  "Mila": [
    "Ahmed Rachedi",
    "Ain Beida Harriche",
    "Ain Mellouk",
    "Ain Tine",
    "Amira Arres",
    "Benyahia Abderrahmane",
    "Bouhatem",
    "Chelghoum Laid",
    "Chigara",
    "Derrahi Bousselah",
    "El Ayadi Barbes",
    "El Mechira",
    "Ferdjioua",
    "Grarem Gouga",
    "Hamala",
    "Mila",
    "Minar Zarza",
    "Oued Athmenia",
    "Oued Endja",
    "Oued Seguen",
    "Ouled Khalouf",
    "Rouached",
    "Sidi Khelifa",
    "Sidi Merouane",
    "Tadjenanet",
    "Tassadane Haddada",
    "Tassala Lematai",
    "Teleghma",
    "Terrai Bainen",
    "Tiberguent",
    "Yahia Beniguecha",
    "Zeghaia"
  ],
  "Ain Defla": [
    "Ain-Benian",
    "Ain-Bouyahia",
    "Ain-Defla",
    "Ain-Lechiakh",
    "Ain-Soltane",
    "Ain-Torki",
    "Arib",
    "Bathia",
    "Belaas",
    "Ben Allal",
    "Bir-Ould-Khelifa",
    "Birbouche",
    "Bordj-Emir-Khaled",
    "Boumedfaa",
    "Bourached",
    "Djelida",
    "Djemaa Ouled Cheikh",
    "Djendel",
    "El-Abadia",
    "El-Amra",
    "El-Attaf",
    "El-Maine",
    "Hammam-Righa",
    "Hassania",
    "Hoceinia",
    "Khemis-Miliana",
    "Mekhatria",
    "Miliana",
    "Oued Chorfa",
    "Oued Djemaa",
    "Rouina",
    "Sidi-Lakhdar",
    "Tacheta Zegagha",
    "Tarik-Ibn-Ziad",
    "Tiberkanine",
    "Zeddine"
  ],
  "Naama": [
    "Ain Ben Khelil",
    "Ain Sefra",
    "Asla",
    "Djenienne Bourezg",
    "El Biodh",
    "Kasdir",
    "Makmen Ben Amar",
    "Mecheria",
    "Moghrar",
    "Naama",
    "Sfissifa",
    "Tiout"
  ],
  "Ain Temouchent": [
    "Aghlal",
    "Ain El Arbaa",
    "Ain Kihal",
    "Ain Temouchent",
    "Ain Tolba",
    "Aoubellil",
    "Beni Saf",
    "Bouzedjar",
    "Chaabat El Ham",
    "Chentouf",
    "El Amria",
    "El Maleh",
    "El Messaid",
    "Emir Abdelkader",
    "Hammam Bou Hadjar",
    "Hassasna",
    "Hassi El Ghella",
    "Oued Berkeche",
    "Oued Sebbah",
    "Ouled Boudjemaa",
    "Ouled Kihal",
    "Oulhaca El Gheraba",
    "Sidi Ben Adda",
    "Sidi Boumediene",
    "Sidi Ouriache",
    "Sidi Safi",
    "Tamzoura",
    "Terga"
  ],
  "Ghardaia": [
    "Berriane",
    "Bounoura",
    "Dhayet Bendhahoua",
    "El Atteuf",
    "El Guerrara",
    "Ghardaia",
    "Mansoura",
    "Metlili",
    "Sebseb",
    "Zelfana"
  ],
  "Relizane": [
    "Ain Rahma",
    "Ain-Tarek",
    "Ammi Moussa",
    "Belaassel Bouzagza",
    "Bendaoud",
    "Beni Dergoun",
    "Beni Zentis",
    "Dar Ben Abdelah",
    "Djidiouia",
    "El H'madna",
    "El Hassi",
    "El Ouldja",
    "El-Guettar",
    "El-Matmar",
    "Had Echkalla",
    "Hamri",
    "Kalaa",
    "Lahlef",
    "Mazouna",
    "Mediouna",
    "Mendes",
    "Merdja Sidi Abed",
    "Ouarizane",
    "Oued El Djemaa",
    "Oued Essalem",
    "Oued-Rhiou",
    "Ouled Aiche",
    "Ouled Sidi Mihoub",
    "Ramka",
    "Relizane",
    "Sidi Khettab",
    "Sidi Lazreg",
    "Sidi M'hamed Benali",
    "Sidi M'hamed Benaouda",
    "Sidi Saada",
    "Souk El Had",
    "Yellel",
    "Zemmoura"
  ],
  "Timimoun": [
    "Aougrout",
    "Charouine",
    "Deldoul",
    "Ksar Kaddour",
    "Metarfa",
    "Ouled Aissa",
    "Ouled Said",
    "Talmine",
    "Timimoun",
    "Tinerkouk"
  ],
  "Bordj Badji Mokhtar": [
    "Bordj Badji Mokhtar",
    "Timiaouine"
  ],
  "Ouled Djellal": [
    "Besbes",
    "Chaiba",
    "Doucen",
    "Ouled Djellal",
    "Ras El Miad",
    "Sidi Khaled"
  ],
  "Beni Abbes": [
    "Beni-Abbes",
    "Beni-Ikhlef",
    "El Ouata",
    "Igli",
    "Kerzaz",
    "Ksabi",
    "Ouled-Khodeir",
    "Tamtert",
    "Timoudi"
  ],
  "In Salah": [
    "Ain Salah",
    "Foggaret Ezzoua",
    "Inghar"
  ],
  "In Guezzam": [
    "Ain Guezzam",
    "Tin Zouatine"
  ],
  "Touggourt": [
    "Benaceur",
    "Blidet Amor",
    "El Alia",
    "El-Hadjira",
    "M'naguer",
    "Megarine",
    "Nezla",
    "Sidi Slimane",
    "Taibet",
    "Tebesbest",
    "Temacine",
    "Touggourt",
    "Zaouia El Abidia"
  ],
  "Djanet": [
    "Bordj El Haouass",
    "Djanet"
  ],
  "El M'Ghair": [
    "Djamaa",
    "El-M'ghaier",
    "M'rara",
    "Oum Touyour",
    "Sidi Amrane",
    "Sidi Khelil",
    "Still",
    "Tenedla"
  ],
  "El Meniaa": [
    "El Meniaa",
    "Hassi Fehal",
    "Hassi Gara"
  ],
  "Aflou": [
    "Aflou",
    "Ain Sidi Ali",
    "Brida",
    "El Beidha",
    "El Ghicha",
    "Gueltat Sidi Saad",
    "Hadj Mechri",
    "Oued M'Zi",
    "Oued Morra",
    "Sebgag",
    "Sidi Bouzid",
    "Taouiala"
  ],
  "Barika": [
    "Abdelkader Azil",
    "Barika",
    "Bitam",
    "Djezzar",
    "M’Doukal",
    "Ouled Ammar",
    "Seggana",
    "Tilatou"
  ],
  "El Kantara": [
    "Ain Zaatout",
    "Branis",
    "Djemourah",
    "El Kantara",
    "El Outaya"
  ],
  "Bir El Ater": [
    "Bir El Ater",
    "El Ogla El Melha",
    "Ferkane",
    "Negrine"
  ],
  "El Aricha": [
    "El Aricha",
    "El Bouihi",
    "El Gor",
    "Sidi Djillali"
  ],
  "Ksar Chellala": [
    "Bougara",
    "Hamadia",
    "Ksar Chellala",
    "Rechaiga",
    "Serguine",
    "Zmalet El Emir Abdelkader"
  ],
  "Ain Oussara": [
    "Ain Fekka",
    "Ain Ouessara",
    "Benhar",
    "Birine",
    "Bouira Lahdab",
    "El Khemis",
    "Guernini",
    "Had Sahary",
    "Hassi Fedoul",
    "Sidi Ladjel"
  ],
  "Messaad": [
    "Amourah",
    "Deldoul",
    "Faidh El Botma",
    "Guettara",
    "Messaad",
    "Oum Laadham",
    "Sed Rahal",
    "Selmana"
  ],
  "Ksar El Boukhari": [
    "Ain Boucif",
    "Ain Ouksir",
    "Aziz",
    "Boghar",
    "Bouaiche",
    "Boughezoul",
    "Chahbounia",
    "Chelalet El Adhaoura",
    "Cheniguel",
    "Derrag",
    "El Ouinet",
    "Kef Lakhdar",
    "Ksar El Boukhari",
    "M’Fatha",
    "Ouled Antar",
    "Ouled Hellal",
    "Ouled Maaref",
    "Oum El Djallil",
    "Saneg",
    "Sidi Damed",
    "Tafraout"
  ],
  "Bou Saada": [
    "Ain El Meleh",
    "Ain Errich",
    "Ain Fares",
    "Ben Srour",
    "Benzouh",
    "Bir Foda",
    "Bou Saada",
    "Djebel Messaad",
    "El Hamel",
    "El Houamed",
    "Khoubana",
    "M’Cif",
    "Medjedel",
    "Menaa",
    "Mouhamed Boudiaf",
    "Ouled Sidi Brahim",
    "Ouled Slimane",
    "Oultem",
    "Sidi Ameur",
    "Sidi M’Hamed",
    "Slim",
    "Tamsa",
    "Zarzour"
  ],
  "El Abiodh Sidi Cheikh": [
    "Ain El Orak",
    "Arbaouat",
    "Boussemghoun",
    "Chellala",
    "El Abiodh Sidi Cheikh",
    "El Bnoud",
    "El Meharra"
  ]
};

export function communesOf(wilaya: string): readonly string[] {
  return COMMUNES_BY_WILAYA[wilaya] ?? [];
}
