-- Ordre de mission → pointage: auto-filled days stay PROPOSED until the user validates the grid.
-- source_code keeps the origin: 'OM' (ordre de mission), 'AUTO' (other correspondences), 'MANUAL' (user).

begin;

alter table public.hr_attendance
  add column if not exists status_code text not null default 'VALIDATED',
  add column if not exists validated_at timestamptz,
  add column if not exists validated_by uuid references public.sys_users(id);

alter table public.hr_attendance drop constraint if exists hr_attendance_status_chk;
alter table public.hr_attendance
  add constraint hr_attendance_status_chk check (status_code in ('PROPOSED', 'VALIDATED'));

create index if not exists hr_attendance_correspondence_idx
  on public.hr_attendance (correspondence_id)
  where correspondence_id is not null;

update public.hr_attendance a
set source_code = 'OM'
from public.hr_correspondences c
where a.correspondence_id = c.id
  and c.type_code = 'OM'
  and a.source_code = 'AUTO';

-- security definer: the ordre is linked to the pointage even when its author
-- has no direct write right on hr_attendance.
create or replace function public.hr_apply_correspondence_attendance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  legend text;
  d date;
  site uuid;
  src text;
begin
  -- UPDATE OF fires whenever the column is in the SET list, even with an unchanged value.
  if tg_op = 'UPDATE'
     and new.type_code is not distinct from old.type_code
     and new.start_date is not distinct from old.start_date
     and new.end_date is not distinct from old.end_date
     and new.site_id is not distinct from old.site_id
     and new.employee_id is not distinct from old.employee_id then
    return new;
  end if;

  -- Days previously generated by this document (not overridden by the user) are rebuilt.
  if tg_op = 'UPDATE' then
    delete from public.hr_attendance
    where correspondence_id = new.id
      and source_code <> 'MANUAL';
  end if;

  select nullif(extra->>'generates_legend', '') into legend
  from public.hr_catalogs
  where kind = 'correspondence_type' and code = new.type_code and is_active
  limit 1;

  if legend is null or new.start_date is null or new.end_date is null then
    return new;
  end if;
  if not exists (select 1 from public.ref_legendes l where l.code = legend and l.is_active) then
    return new;
  end if;

  site := new.site_id;
  if site is null then
    select c.site_id into site
    from public.hr_contracts c
    where c.employee_id = new.employee_id
      and c.affectation_principale
      and c.status in ('ACTIVE', 'DRAFT', 'SUSPENDED')
    order by (c.status = 'ACTIVE') desc, c.start_date desc
    limit 1;
  end if;
  if site is null then
    return new;
  end if;

  src := case when new.type_code = 'OM' then 'OM' else 'AUTO' end;

  d := new.start_date;
  while d <= new.end_date loop
    insert into public.hr_attendance (
      employee_id, site_id, work_date, legend_code, source_code,
      correspondence_id, status_code, validated_at, validated_by
    ) values (
      new.employee_id, site, d, legend, src,
      new.id, 'PROPOSED', null, null
    )
    on conflict (employee_id, site_id, work_date) do update set
      legend_code = excluded.legend_code,
      source_code = excluded.source_code,
      correspondence_id = excluded.correspondence_id,
      status_code = 'PROPOSED',
      validated_at = null,
      validated_by = null,
      updated_at = now()
    where public.hr_attendance.source_code <> 'MANUAL';
    d := d + 1;
  end loop;
  return new;
end;
$$;

drop trigger if exists trg_hr_corr_attendance on public.hr_correspondences;
create trigger trg_hr_corr_attendance
  after insert or update of type_code, start_date, end_date, site_id, employee_id
  on public.hr_correspondences
  for each row execute function public.hr_apply_correspondence_attendance();

commit;
